[[permission]]
identifier = "allow-all-app-commands"
description = "Allows access to all main application custom commands"
commands.allow = [
    "get_settings",
    "save_settings",
    "show_settings",
    "hide_menu",
    "execute_action",
    "execute_sub_action",
    "get_current_media_info",
    "get_system_stats",
    "is_hotkey_held",
    "control_media",
    "get_scripts",
    "save_script",
    "delete_script",
    "get_events",
    "save_events",
    "show_assistant",
    "run_terminal_command",
    "spawn_terminal_command",
    "write_file",
    "create_directory",
    "read_file",
    "list_directory",
    "get_custom_modules",
    "save_custom_module",
    "delete_custom_module",
    "get_plugins",
    "save_plugin",
    "delete_plugin",
    "search_files",
    "edit_file_content",
    "get_app_state",
    "get_active_app",
    "show_project_board",
    "show_ai_terminal",
    "show_design_maker",
    "import_plugin",
    "export_plugin",
    "get_plugin_settings",
    "save_plugin_settings"
]
