#!/usr/bin/env python3
"""Put PRD live on PythonAnywhere in one command.

Run it either place:

* **In a PythonAnywhere Bash console**, after cloning the repo — it uses the
  files already on disk and only calls the API to configure the web app.
* **From your own computer** — add ``--upload`` and it pushes the whole project
  through the Files API first.

It creates the web app if you don't have one, writes the WSGI file, generates a
``.env`` with fresh secrets, maps ``/sites/`` and ``/static/`` so nginx serves
them directly, and reloads. Nothing is overwritten without being asked.

    export PYTHONANYWHERE_API_TOKEN=...
    python3 deploy_pythonanywhere.py --admin-password 'something private'
"""
from __future__ import annotations

import argparse
import os
import secrets
import sys
from pathlib import Path

PROJECT_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(PROJECT_DIR))

from prd_app.config import PythonAnywhereConfig  # noqa: E402
from prd_app.deploy.pythonanywhere import (  # noqa: E402
    PythonAnywhereClient, PythonAnywhereError,
)

HOSTS = ("www.pythonanywhere.com", "eu.pythonanywhere.com")


def load_env_file() -> None:
    """A deployed instance already keeps its token in .env; reuse it.

    Real environment variables still win, so an explicit token or username on
    the command line overrides whatever the file says.
    """
    env_file = PROJECT_DIR / ".env"
    if not env_file.exists():
        return
    for line in env_file.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


load_env_file()

# The create-webapp endpoint wants "python310", not "3.10".
PYTHON_VERSIONS = {
    "3.9": "python39", "3.10": "python310", "3.11": "python311",
    "3.12": "python312", "3.13": "python313",
}

SKIP_DIRS = {".git", "__pycache__", ".venv", "venv", ".prd-data", ".pytest_cache",
             ".mypy_cache", "node_modules", ".idea", ".vscode"}
SKIP_SUFFIXES = {".pyc", ".pyo", ".sqlite3", ".sqlite3-wal", ".sqlite3-shm", ".log"}
SKIP_NAMES = {".env", ".DS_Store"}

WSGI_TEMPLATE = '''"""WSGI entry point for PRD. Generated by deploy_pythonanywhere.py."""
import sys

PROJECT_DIR = "{project_dir}"
if PROJECT_DIR not in sys.path:
    sys.path.insert(0, PROJECT_DIR)

from wsgi import application  # noqa: E402,F401
'''


def api_python_version(value: str) -> str:
    """Accept "3.10", "python310" or "3.10.4" and return what the API expects."""
    raw = (value or "").strip().lower()
    if raw.startswith("python"):
        return raw
    parts = raw.split(".")
    if len(parts) >= 2 and parts[0].isdigit() and parts[1].isdigit():
        return f"python{parts[0]}{parts[1]}"
    if raw.isdigit():
        return f"python{raw}"
    fail(f"'{value}' is not a Python version. Try one of: {', '.join(PYTHON_VERSIONS)}")


def log(message: str) -> None:
    print(message, flush=True)


def fail(message: str) -> "NoReturn":  # type: ignore[valid-type]
    print(f"\n✗ {message}", file=sys.stderr)
    raise SystemExit(1)


# ---------------------------------------------------------------------------
# Discovery
# ---------------------------------------------------------------------------

def running_on_pythonanywhere() -> bool:
    return Path("/var/www").is_dir() and Path.home().parent.name == "home"


def guess_username() -> str:
    for value in (os.environ.get("PYTHONANYWHERE_USERNAME"), os.environ.get("USER"),
                  Path.home().name):
        if value and value not in ("root", "www-data"):
            return value
    return ""


def find_host(token: str, username: str, preferred: str = "") -> tuple[str, PythonAnywhereClient]:
    """Try each API host until one accepts the token for this username."""
    problems = []
    for host in ([preferred] if preferred else []) + [h for h in HOSTS if h != preferred]:
        config = PythonAnywhereConfig(token=token, username=username, host=host)
        client = PythonAnywhereClient(config)
        try:
            client.whoami()
        except PythonAnywhereError as exc:
            problems.append(f"  {host}: {exc}")
            continue
        return host, client
    fail("The API token was not accepted for user '{}'.\n{}\n\n"
         "Check the username and that the token comes from the same site "
         "(www. and eu. accounts have separate tokens):\n"
         "  https://www.pythonanywhere.com/account/#api_token"
         .format(username, "\n".join(problems)))


# ---------------------------------------------------------------------------
# Steps
# ---------------------------------------------------------------------------

def iter_project_files(root: Path):
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        if any(part in SKIP_DIRS for part in path.relative_to(root).parts):
            continue
        if path.suffix in SKIP_SUFFIXES or path.name in SKIP_NAMES:
            continue
        yield path


def upload_project(client: PythonAnywhereClient, root: Path, remote_dir: str) -> int:
    count = 0
    for path in iter_project_files(root):
        relative = path.relative_to(root).as_posix()
        client.upload(f"{remote_dir}/{relative}", path.read_bytes())
        count += 1
        if count % 10 == 0:
            log(f"    …{count} files")
    return count


def build_env(*, username: str, host: str, domain: str, data_dir: str,
              admin_password: str, auto_approve: bool, token: str) -> str:
    return "\n".join([
        "# Generated by deploy_pythonanywhere.py — keep this file private.",
        f"PRD_SECRET_KEY={secrets.token_hex(32)}",
        f"PRD_IP_SALT={secrets.token_hex(16)}",
        f"PRD_ADMIN_PASSWORD={admin_password}",
        f"PRD_DB_PATH={data_dir}/prd.sqlite3",
        f"PRD_SITES_ROOT={data_dir}/sites",
        f"PRD_BASE_URL=https://{domain}",
        "PRD_DEPLOY_TARGET=pythonanywhere",
        f"PRD_AUTO_APPROVE={'1' if auto_approve else '0'}",
        "",
        f"PYTHONANYWHERE_API_TOKEN={token}",
        f"PYTHONANYWHERE_USERNAME={username}",
        f"PYTHONANYWHERE_HOST={host}",
        f"PYTHONANYWHERE_DOMAIN={domain}",
        f"PYTHONANYWHERE_SITES_DIR={data_dir}/sites",
        "PYTHONANYWHERE_SITES_URL=/sites/",
        "",
    ])


def ensure_static_mapping(client: PythonAnywhereClient, domain: str, url: str, path: str,
                          dry: bool = False) -> None:
    for mapping in client.static_mappings(domain):
        if mapping.get("url") == url:
            if (mapping.get("path") or "").rstrip("/") != path.rstrip("/"):
                log(f"  ! {url} already points at {mapping.get('path')} — leaving it alone")
            else:
                log(f"  · {url} already mapped")
            return
    if dry:
        log(f"  would map {url} → {path}")
        return
    client.add_static_mapping(domain, url, path)
    log(f"  + mapped {url} → {path}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Deploy PRD to PythonAnywhere.")
    parser.add_argument("--token", default=os.environ.get("PYTHONANYWHERE_API_TOKEN", ""),
                        help="API token (default: $PYTHONANYWHERE_API_TOKEN)")
    parser.add_argument("--username", default=guess_username(),
                        help="PythonAnywhere username")
    parser.add_argument("--host", default=os.environ.get("PYTHONANYWHERE_HOST", ""),
                        choices=[*HOSTS, ""], help="API host (auto-detected by default)")
    parser.add_argument("--domain", default="", help="Web app domain (default: <user>.pythonanywhere.com)")
    parser.add_argument("--python-version", default="3.10",
                        help="Python version for a new web app, e.g. 3.10 (default) or 3.11")
    parser.add_argument("--project-dir", default="", help="Where the code lives on PythonAnywhere")
    parser.add_argument("--data-dir", default="", help="Where the database and sites live")
    parser.add_argument("--virtualenv", default="", help="Virtualenv path to attach to the web app")
    parser.add_argument("--admin-password", default=os.environ.get("PRD_ADMIN_PASSWORD", ""),
                        help="Password for the owner dashboard (generated if omitted)")
    parser.add_argument("--auto-approve", action="store_true",
                        help="Publish requests instantly instead of queueing them for review")
    parser.add_argument("--upload", action="store_true",
                        help="Push the project files through the API (implied when not on PythonAnywhere)")
    parser.add_argument("--replace-webapp", action="store_true",
                        help="Repoint an existing web app at PRD (it will stop serving whatever it serves now)")
    parser.add_argument("--keep-env", action="store_true",
                        help="Leave an existing .env alone instead of writing a new one")
    parser.add_argument("--dry-run", action="store_true",
                        help="Show what would happen without changing anything on your account")
    args = parser.parse_args()

    if not args.token:
        fail("No API token. Set PYTHONANYWHERE_API_TOKEN or pass --token.\n"
             "Create one at https://www.pythonanywhere.com/account/#api_token")
    if not args.username:
        fail("Could not work out your PythonAnywhere username — pass --username.")

    username = args.username
    domain = args.domain or f"{username}.pythonanywhere.com"
    project_dir = args.project_dir or f"/home/{username}/projects/prd"
    data_dir = args.data_dir or f"/home/{username}/prd-data"
    on_pa = running_on_pythonanywhere()
    upload = args.upload or not on_pa

    log(f"→ Deploying PRD as {username} ({domain})")
    log(f"  code: {project_dir}")
    log(f"  data: {data_dir}")
    log(f"  running {'on PythonAnywhere' if on_pa else 'locally, uploading over the API'}")

    host, client = find_host(args.token, username, args.host)
    log(f"✓ API token accepted on {host}")

    # 1. The web app itself -------------------------------------------------
    python_version = api_python_version(args.python_version)
    existing = next((app for app in client.webapps() if app.get("domain_name") == domain), None)
    if existing is None:
        log(f"→ Creating the web app {domain} (Python {args.python_version} → {python_version})")
        if args.dry_run:
            log("  would create it")
        else:
            try:
                client.create_webapp(domain, python_version)
            except PythonAnywhereError as exc:
                if "python_version" in str(exc) or "Python version" in str(exc):
                    fail(f"{exc}\n\nThat Python version is not available on your account. "
                         f"Try another with --python-version, for example:\n"
                         f"  python3 deploy_pythonanywhere.py --username {username} --python-version 3.11")
                raise
            log("✓ Web app created")
    else:
        serving = existing.get("source_directory") or "(unset)"
        if serving.rstrip("/") != project_dir.rstrip("/") and not args.replace_webapp:
            fail(f"{domain} already exists and serves {serving}.\n"
                 f"Re-run with --replace-webapp to point it at PRD instead, or pass\n"
                 f"--domain with a different domain if your account allows more than one.")
        log(f"· Web app {domain} already exists — reusing it")

    fields = {"source_directory": project_dir}
    if args.virtualenv:
        fields["virtualenv_path"] = args.virtualenv
    if args.dry_run:
        log(f"  would set {fields}")
    else:
        client.update_webapp(domain, **fields)
        log("✓ Web app configured")

    # 2. Code ---------------------------------------------------------------
    if upload:
        log("→ Uploading project files")
        if args.dry_run:
            count = sum(1 for _ in iter_project_files(PROJECT_DIR))
            log(f"  would upload {count} files to {project_dir}")
        else:
            count = upload_project(client, PROJECT_DIR, project_dir)
            log(f"✓ Uploaded {count} files")
    else:
        log("· Using the files already on disk")

    # 3. Configuration ------------------------------------------------------
    env_path = f"{project_dir}/.env"
    existing_env = client.read_file(env_path)
    if existing_env and args.keep_env:
        log("· Keeping the existing .env")
        admin_password = ""
    else:
        if existing_env:
            log("  ! Replacing the existing .env (pass --keep-env to keep it)")
        admin_password = args.admin_password or secrets.token_urlsafe(12)
        env_body = build_env(
            username=username, host=host, domain=domain, data_dir=data_dir,
            admin_password=admin_password, auto_approve=args.auto_approve, token=args.token,
        )
        if args.dry_run:
            log(f"  would write {env_path}:")
            for line in env_body.splitlines():
                key = line.split("=", 1)[0]
                secret = key in ("PRD_SECRET_KEY", "PRD_IP_SALT", "PRD_ADMIN_PASSWORD",
                                 "PYTHONANYWHERE_API_TOKEN")
                log(f"      {key}=<generated>" if secret and line else f"      {line}")
        else:
            client.upload(env_path, env_body)
            log("✓ Wrote .env with fresh secrets")

    # Uploading a file creates its parent directories, which is how the data
    # directory comes into existence.
    if args.dry_run:
        log(f"  would create {data_dir}/sites/")
    else:
        client.upload(f"{data_dir}/sites/.prd-keep", "This directory holds published sites.\n")
        log("✓ Data directory ready")

    # 4. WSGI ---------------------------------------------------------------
    wsgi_remote = f"/var/www/{domain.replace('.', '_')}_wsgi.py"
    wsgi_body = WSGI_TEMPLATE.format(project_dir=project_dir)
    wsgi_written = True
    if args.dry_run:
        log(f"  would write {wsgi_remote}")
    else:
        try:
            client.upload(wsgi_remote, wsgi_body)
            log(f"✓ Wrote {wsgi_remote}")
        except PythonAnywhereError as exc:
            # Everything else is already in place, so finish the deploy and tell
            # them the one thing left to paste rather than throwing it all away.
            wsgi_written = False
            log(f"  ! Could not write {wsgi_remote}: {exc}")

    # 5. Static files -------------------------------------------------------
    log("→ Static file mappings")
    ensure_static_mapping(client, domain, "/sites/", f"{data_dir}/sites", args.dry_run)
    ensure_static_mapping(client, domain, "/static/", f"{project_dir}/prd_app/static", args.dry_run)

    # 6. Go ------------------------------------------------------------------
    if args.dry_run:
        log("")
        log("Dry run — nothing on your account was touched.")
        log("Re-run without --dry-run to deploy for real.")
        return 0

    log("→ Reloading the web app")
    client.reload(domain)

    log("")
    log("=" * 62)
    log(f"  PRD is live:      https://{domain}/")
    log(f"  Owner dashboard:  https://{domain}/admin")
    if admin_password:
        log(f"  Owner password:   {admin_password}")
    log("=" * 62)
    if not wsgi_written:
        log("")
        log("One manual step left — the WSGI file could not be written over the API.")
        log(f"Open the Web tab, click the WSGI configuration file link, and replace it with:")
        log("")
        for line in wsgi_body.splitlines():
            log(f"    {line}")
        log("")
        log("Then hit Reload.")
    log("")
    log("If the site shows an error, check the log at")
    log(f"  https://{host}/user/{username}/files/var/log/{domain}.error.log")
    log("The usual cause is Flask missing from the web app's Python — install it with")
    log(f"  pip3.10 install --user Flask requests")
    log("in a Bash console, then hit Reload on the Web tab.")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except PythonAnywhereError as exc:
        fail(str(exc))
    except KeyboardInterrupt:
        fail("Cancelled.")
